# Generated by Django 2.2.19 on 2021-03-14 08:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'app_location',
            },
        ),
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('country_code', models.IntegerField(default=1)),
                ('national_number', models.BigIntegerField()),
                ('validated', models.BooleanField(default=False)),
                ('location', models.ManyToManyField(related_name='number_location', to='locate.Location')),
            ],
            options={
                'db_table': 'app_number',
                'unique_together': {('country_code', 'national_number')},
            },
        ),
    ]
