# Generated by Django 2.2.19 on 2021-03-14 04:34

from django.db import migrations, models
import uuid

def load_initial_keyword(apps, schema_editor):
    """
    load initial keyword
    """
    Keyword = apps.get_model("keyword", "Keyword")
    keyword, _ = Keyword.objects.get_or_create(
        country_code=1, national_number=3101231234)
    keyword.location = 'America/Los_Angeles'
    keyword.save()

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('country_code', models.IntegerField(default=1)),
                ('national_number', models.BigIntegerField()),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'app_keyword',
            },
        ),
        migrations.RunPython(load_initial_keyword),
    ]
